versions: "3"
services:
    web:
        image: test
        deploy:
            replicas: 5
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
            ports:
                - "5001:5000"
            networks:
                - webnet
networks:
    webnet:
